// ASPNET_MVC_Framework_EntityCRUD_2/react-task-tracker/react-task-tracker/src/components/Header.js
import React from 'react'
import Button from './Button'
import { useLocation } from 'react-router-dom'

const Header = ({ title, onAdd, showAdd }) => {
    const location = useLocation()

    return (
        <header className='header'>
            <h1 style={{ color: 'green' }}>{title}</h1>
            {location.pathname === '/' ? <Button
                color={showAdd ? 'red' : 'green'}
                text={showAdd ? 'Close' : 'Add'}
                onClick={onAdd} />
                : ''
            }
        </header>
    )
}

Header.defaultProps = {
    title: 'Task tracker'
}

export default Header

// ASPNET_MVC_Framework_EntityCRUD_2/angular-task-tracker/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  title: string = 'Task Tracker';
  
  constructor() { }

  ngOnInit(): void {
  }

  toggleAddTask(){
    console.log('toggle');
  }

}

<header>
    <h1>{{ title }}</h1>
    <app-button *ngIf="hasRoute('/')" 
    color="{{showAddTask ? 'red' : 'green'}}" 
    text="{{showAddTask ? 'Close' : 'Add'}}" 
    (btnClick)="toggleAddTask()"></app-button>
</header>
