// ASPNET_MVC_Framework_EntityCRUD_2/angular-task-tracker/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from '../../Task'
import { UiService } from 'src/app/services/ui.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter();
  text!: string;
  day!: string;
  reminder: boolean = false;
  showAddTask!: boolean;
  subscription!: Subscription;

  constructor(private uiService: UiService) {
    this.subscription = this.uiService.onToggle().subscribe(
      (value) => (this.showAddTask = value)
    );
  }

  ngOnInit(): void {
  }

  onSubmit() {
    if (!this.text) {
      alert('please add a task');
      return;
    }

    const newTask: Task = {
      text: this.text,
      day: this.day,
      reminder: this.reminder
    }

    this.onAddTask.emit(newTask); //cia emitinam, bet jeigu blogas response clear values ivyksta

    this.clearValues();
  }

  clearValues() {
    this.text = '';
    this.day = '';
    this.reminder = false;
  }

}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" [(ngModel)]="text" id="text" placeholder="Add Task" />
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="datetime-local" name="day" [(ngModel)]="day" id="day" />
    </div>
    <div class="form-control form-control-check">
        <label for="reminder">Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder" />
    </div>
    <input type="submit" value="Save Task" class="btn btn-block" />
</form>

// ASPNET_MVC_Framework_EntityCRUD_2/react-task-tracker/react-task-tracker/src/components/AddTask.js
import React from 'react'
import { useState } from 'react'


const AddTask = ({ onAdd } ) => {
    const [text, setText] = useState('');
    const [day, setDay] = useState('');
    const [reminder, setReminder] = useState(false);

    const onSubmit = (e) => {
        e.preventDefault();

        if(!text){
            alert('please add a task')
            return
        }

        onAdd({text,day,reminder})

        setText('')
        setDay('')
        setReminder(false)
    }

    return (
        <form className='add-form' onSubmit={onSubmit}>
            <div className='form-control'>
                <label>Task</label>
                <input type='text' placeholder='Add Task' value={text}
                    onChange={
                        (e) => setText(e.target.value)
                    } />
            </div>
            <div className='form-control'>
                <label>Day and time</label>
                <input type='datetime-local' value={day}
                    onChange={
                        (e) => setDay(e.target.value)
                    } />
            </div>
            <div className='form-control form-control-check'>
                <label>Set Reminder</label>
                <input type='checkbox' value={reminder} checked={reminder}
                    onChange={
                        (e) => setReminder(e.currentTarget.checked)
                    } />
            </div>

            <input type='submit' value='Save Task' className='btn btn-block' />
        </form>
    )
}

export default AddTask
